<div class="impresario-login-template" style="display:none">
    <div class="login-form-template">
        <section>
            <div class="input-group user-group">
                <div class="input-group-append">
                    <span class="input-group-text">
                        <i class="fa fa-user"></i>
                    </span>
                </div>
            </div>

             <div class="input-group pass-group">
                <div class="input-group-append">
                    <span class="input-group-text">
                        <i class="fa fa-key"></i> 
                    </span>
                </div>
            </div>
        </section>

        <section class="controls">
            <div class="checkbox check-transparent remember-group">
                
                <label for="remember">Remember me</label>
            </div>
            <a href="#">Forget password?</a>
        </section>
    </div>
</div>