<div class="impresario-login-template" style="display:none">
<!-- Login form -->
    <div class="login-form-template">
        <section>
            <div class="input-group user-group">
                <div class="input-group-append">
                    <span class="input-group-text">
                        <i class="fa fa-user"></i>
                    </span>
                </div>
            </div>

             <div class="input-group pass-group">
                <div class="input-group-append">
                    <span class="input-group-text">
                        <i class="fa fa-key"></i> 
                    </span>
                </div>
            </div>
        </section>

        <section class="controls">
            <div class="checkbox check-transparent remember-group">
                
                <label for="remember">Remember me</label>
            </div>
            <a href="<?php echo wp_lostpassword_url();?>" class="btn btn-red btn-sm">Forget password?</a>
        </section>

        <section class="log-in">
            <button type="submit" class="btn btn-primary btn-md">Log In</button>
        </section>
    </div>
<!-- Lost Password -->
    <div class="lostpassword-form-template">
        <section>
            <div class="input-group user-group">
                <div class="input-group-append">
                    <span class="input-group-text">
                        <i class="fa fa-user"></i>
                    </span>
                </div>
            </div>
        </section>

        <section class="forgot-pass">
            <button type="submit" class="btn btn-primary btn-md">Reset Password</button>
        </section>
    </div>

    <div class="resetpassword-form-template">
        <section>
            <div class="input-group pass-group password-input-wrapper show-password">
                
            </div>
        </section>

        <section>
            <div class="strength-result"></div>
        </section>

         <section class="controls user-pass1-wrap">
            <div class="checkbox check-transparent weak-pw-group pw-weak">
                
                <label for="weak-pw-accept">Confirm use of weak password</label>
            </div>
        </section>

        <section>
            <div class="password-advice"></div>
        </section>

        <section class="forgot-pass">
            <button type="submit" name="wp-submit" id="wp-submit"  class="btn btn-primary btn-md">Reset Password</button>
        </section>
    </div>
</div>