<?php
/**  @var \DaveBaker\Core\Block\Template $block */
?>
<ul>
    <li>
        <a href="<?php echo $block->getPageUrl(\SuttonBaker\Impresario\Definition\Page::TASK_LIST);?>"><?php echo $this->_('All Tasks');?></a>
    </li>
    <li>
        <a href="<?php echo $block->getPageUrl(\SuttonBaker\Impresario\Definition\Page::TASK_LIST, ['completed' => 1]);?>"><?php echo $this->_('Completed Tasks');?></a>
    </li>
</ul>