<?php /** @var \SuttonBaker\Impresario\Block\Structure\Nav $block */?>
<ul class="menu">
    <?php foreach($block->getNavItems() as $navItem):?>
        <li>
            <a href="<?php echo $navItem['link'];?>">
                <i class="fa fa-tachometer"></i> <?php echo $block->_($navItem['name']);?>
                <!--            <span class="badge badge-red">1</span>-->
            </a>
        </li>
    <?php endforeach; ?>
</ul>