<?php

/** @var \SuttonBaker\Impresario\Block\Cost\PrintPO $block **/

$poItems = $block->getPOItems();
?>

<div class="container bg-white p-4">
    <div class="row pb-4">
        <!-- Left column start -->
        <div class="col-md">
            <!-- Logo and address -->
            <div class="pb-2">
                <div class="w-50">
                    <img src="<?php echo $block->getLogo(); ?>" class="img-fluid" />
                </div>

                <address class="h5 pl-2">
                    Camp Farm Barn,<br />
                    Knowle Hill,<br />
                    Hurley,<br />
                    CV9 2JF
                </address>
            </div>

        </div>
        <!-- Left column end -->

        <!-- Right column start - bootstrap resets print table backgrounds, hence they're inlined here -->
        <div class="col-md">
            <h5 class="uppercase text-center">Purchase Order</h5>
            <table class="table table-sm table-bordered border-dark">
                <tr>
                    <th class="bg-secondary text-white" style="background: #6c757d !important;">Date:</th>
                    <td><?= $block->escapeHtml($block->getCostDate()); ?></td>
                </tr>

                <tr>
                    <th class="bg-secondary text-white" style="background: #6c757d !important;">Project No:</th>
                    <td><?= $block->escapeHtml($block->getCost()->getParentId()); ?></td>
                </tr>

                <tr>
                    <th class="bg-secondary text-white" style="background: #6c757d !important;">Client:</th>
                    <td><?= $block->escapeHtml($block->getClientName()); ?></td>
                </tr>

                <tr>
                    <th class="bg-secondary text-white" style="background: #6c757d !important;">Supplier Quote Number:</th>
                    <td><?= $block->escapeHtml($block->getSupplierQuoteNumber()); ?></td>
                </tr>

                <tr>
                    <th class="bg-secondary text-white" style="background: #6c757d !important;">PO Number:</th>
                    <td><?= $block->escapeHtml($block->getCost()->getId()) ?></td>
                </tr>
            </table>
        </div>
    </div>



    <div class="row flex d-flex h-100 pb-4">
        <div class="col-md">
            <div class="border border-dark d-flex flex-column h-100">
                <div class="bg-secondary text-white p-1">Supplier</div>
                <!--This is already escaped by the block -->
                <div class="p-1"><?= $block->getSupplierAddress(); ?></div>
            </div>
        </div>

        <div class="col-md">
            <div class="border border-dark d-flex flex-column h-100">
                <div class="bg-secondary text-white p-1">Site</div>
                <div class="p-1"><?= $block->escapeHtml($block->getSiteName()); ?></div>

                <div class="mt-auto">
                    <table class="table table-sm table-bordered border-dark">
                        <tr>
                            <th class="bg-secondary text-white" style="background: #6c757d !important;">Delivery Date</th>
                            <td class="w-50"><?= $block->escapeHtml($block->getDeliveryDate()); ?></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="row pb-4">
        <div class="col">
            <table class="table table-sm table-bordered border-dark">
                <tr>
                    <th class="bg-secondary text-white" style="background: #6c757d !important;">Requested By (PM):</th>
                    <td class="w-50"><?= $block->escapeHtml($block->getProjectManagerName()); ?></td>
                </tr>
            </table>
        </div>
    </div>

    <?php if (count($poItems)) : ?>
        <div class="row pb-4">
            <div class="col">
                <table class="table table-sm table-bordered border-dark text-center">
                    <thead>
                        <th class="bg-secondary text-white" style="background: #6c757d !important;">Description</th>
                        <th class="bg-secondary text-white" style="background: #6c757d !important;">Qty</th>
                        <th class="bg-secondary text-white" style="background: #6c757d !important;">Unit Price</th>
                        <th class="bg-secondary text-white" style="background: #6c757d !important;">Total</th>
                    </thead>
                    <tbody>
                        <?php foreach ($poItems as $poItem) : ?>
                            <tr>
                                <td><?= $block->escapeHtml($poItem->getDescription()); ?></td>
                                <td><?= $block->escapeHtml((int) $poItem->getQty()); ?></td>
                                <td><?= $block->escapeHtml($this->formatCurrency($poItem->getUnitPrice())); ?></td>
                                <td><?= $block->escapeHtml($this->formatCurrency($poItem->getTotal())); ?></td>
                            <tr>
                            <?php endforeach; ?>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td class="" colspan="2">&nbsp;</td>
                            <td class="bg-secondary text-white text-right font-weight-bold" style="background: #6c757d !important;">Total</td>
                            <td class="bg-secondary text-white font-weight-bold" style="background: #6c757d !important;"><?= $block->escapeHtml($this->formatCurrency($block->getCost()->getPoItemTotal())); ?></td>
                        <tr>
                    </tfoot>
                </table>
            </div>
        </div>
    <?php endif; ?>

    <div class="wpb_wrapper" style="page-break-before: always; padding:20px">
        <h2>Terms and Conditions</h2>
		<p class="p1"><strong>1. <strong>Application</strong></strong></p>
<p class="p2"><span class="s1">1.1 </span>These Terms and Conditions shall apply to the provision of Services by the Supplier to the Client.</p>
<p class="p3"><span class="s1">1.2 </span>In the event of conflict between these Terms and Conditions and any other terms and conditions (of the Supplier or otherwise), the former shall prevail unless expressly otherwise agreed by the Client in writing.</p>
<p class="p1"><strong>2. Definitions</strong></p>
<p class="p2"><span class="s1">2.1 </span>In this Agreement, unless the context otherwise requires, the following expressions have the following meanings:</p>
<table class="t1" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td class="td1" valign="top">
<p class="p2"><b>“Business Day” </b></p>
</td>
<td class="td1" valign="top">
<p class="p2">a day (excluding Saturdays) on which banks generally are open for the transaction of normal banking business (other than solely for trading and settlement in euros);</p>
</td>
</tr>
<tr>
<td class="td1" valign="top">
<p class="p2"><b>“The Client” </b></p>
</td>
<td class="td1" valign="top">
<p class="p2">T&amp;D Design and build Limited</p>
</td>
</tr>
<tr>
<td class="td1" valign="top">
<p class="p2"><b>“The Commencement Date” </b></p>
</td>
<td class="td1" valign="top">
<p class="p2">the commencement date for this agreement as set out in the schedule or as</p>
</td>
</tr>
<tr>
<td class="td1" valign="top">
<p class="p2"><b>“ Services” </b></p>
</td>
<td class="td1" valign="top">
<p class="p2">means the services to be provided by the Supplier to the Clients as set out in the schedule/quotation/letter or as otherwise agreed with the Client</p>
</td>
</tr>
<tr>
<td class="td1" valign="top">
<p class="p2"><b>“The Supplier” </b></p>
</td>
<td class="td1" valign="top">
<p class="p3">means any individual, firm or corporate body (which expression shall, where the context so admits, include its successors and assigns) which provides services for or on behalf of the Client</p>
</td>
</tr>
</tbody>
</table>
<p><span class="s1">2.2 </span>Any reference in these Conditions to a statute or a provision of a statute shall be construed as a reference to that statute or provision as amended, re-enacted or extended at the relevant time.</p>
<p class="p3"><span class="s1">2.3 </span>The headings in these Conditions are for convenience only and shall not affect their interpretation.</p>
<p class="p2"><span class="s1">3. </span><b>The Service</b></p>
<p class="p2"><span class="s1">3.1 </span>With effect from the Commencement Date the Supplier shall, in consideration of the Fees being paid in accordance with the Terms of Payment will provide the services expressly identified in the schedule/quotation/letter or otherwise agreed under this agreement.</p>
<p class="p2"><span class="s1">3.2 </span>The Supplier will use reasonable care and skill to perform the services identified in the schedule/quotation/letter or otherwise agreed under this agreement.</p>
<p class="p3"><span class="s1">3.3 </span>The Supplier shall use all reasonable endeavours to complete its obligations under the schedule/quotation/letter, and time shall be of the essence in the performance of these obligations.</p>
<p class="p1"><strong>4. <strong>Price</strong></strong></p>
<p class="p2"><span class="s1">4.1 </span>The Client agrees to pay the Fees in accordance with the terms of payment.</p>
<p class="p2"><span class="s1">4.2 </span>In addition, the Supplier shall be entitled to recover from the Client his reasonable incidental expenses for materials used and for third party goods and services supplied in connection with the provision of the Services or as otherwise agreed under this agreement.</p>
<p class="p2"><span class="s1">4.3 </span>The Client will pay the Supplier for any additional services provided by the Supplier that are not specified in the schedule/quotation/letter or as otherwise agreed under this agreement in accordance with the Supplier’s then current, applicable daily rate in effect at the time of the performance or such other rate as may be agreed. Any charge for additional services will be supplemental to the amounts that may be due for the Expenses.</p>
<p class="p3"><span class="s1">4.4 </span>All sums payable by either party pursuant to this Agreement are exclusive of any value added or other tax (except corporation tax) or other taxes on profit, for which that party shall be additionally liable.</p>
<p class="p1"><strong>5. <strong>Payment</strong></strong></p>
<p class="p4"><span class="s1">5.1 </span>All payments required to be made pursuant to this Agreement by either party shall be made within 60 days of the date of the relevant invoice in pounds sterling in cleared funds to such bank in the United Kingdom as the other party may from time to time nominate, without any set-off, withholding or deduction except such amount (if any) of tax as that party is required to deduct or withhold by law.</p>
<p class="p5"><span class="s1">5.2 </span>All payments are subject to The Client receiving all relevant proofs/certificates/paperwork as required of work done and are also subject to routine inspection returning adequate quality assurance by The Client or an independent inspection at the discretion of The Client or otherwise agreed under this agreement. Any invoice shall not be deemed to be due until sixty days after all relevant proofs/certificates/paperwork have been received in the correct format from the supplier.</p>
<p class="p1"><strong>6. <strong>Variation and amendments</strong></strong></p>
<p class="p2"><span class="s1">6.1 </span>If the Client wishes to vary any details of the schedule/quotation/letter it must notify the Supplier in writing as soon as possible. The Supplier shall endeavour to make any required changes and any additional costs thereby incurred shall be invoiced to the Client.</p>
<p class="p3"><span class="s1">6.2 </span>If, due to circumstances beyond the Supplier’s control, it has to make any change in the arrangements relating to the provision of the Services it shall notify the Client forthwith. The Supplier shall endeavour to keep such changes to a minimum and shall seek to offer the Client arrangements as close to the original as is reasonably possible in the circumstances.</p>
<p class="p1"><strong>7. <strong>Termination</strong></strong></p>
<p class="p2"><span class="s1">7.1 </span>The Client may terminate the agreement forthwith if: <span class="s1">7.1.1 </span>the Supplier is in breach of any of its obligations hereunder; or</p>
<p class="p2" style="padding-left: 40px;"><span class="s1">7.1.2 </span>the Supplier has entered into liquidation (other than for the purposes of a bona fide amalgamation or reconstruction) whether compulsory or voluntarily or compounds with its creditors generally or has an administrator, administrative receiver or receiver appointed over all or a substantial part of its undertaking or assets; or</p>
<p class="p2" style="padding-left: 40px;"><span class="s1">7.1.3 </span>the Supplier has become bankrupt or shall be deemed unable to pay its debts by virtue of Section 123 of the Insolvency Act 1986; or</p>
<p class="p2" style="padding-left: 40px;"><span class="s1">7.1.4 </span>the Supplier ceases or threatens to cease to carry on business; or</p>
<p class="p3" style="padding-left: 40px;"><span class="s1">7.1.5 </span>any circumstances whatsoever beyond the reasonable control of the Client (including but not limited to the termination of the service through no fault of the Client) arise that necessitate for whatever reason the termination of the provision of services.</p>
<p class="p1"><strong>8. <strong>Sub-Contracting</strong></strong></p>
<p class="p1">Either party may sub-contract the performance of any of its obligations under this Agreement without the prior written consent of the other party. Where either party sub-contracts the performance of any of its obligation under this Agreement to any person with the prior consent of the other party, that party shall be responsible for every act or omission of the sub-contractor as if it were an act or omission of the party itself.</p>
<p class="p1"><strong>9. <strong>Liability</strong></strong></p>
<p class="p2"><span class="s1">9.1 </span>Except in respect of death or personal injury caused by The Client’s negligence, the Client will not by reason of any representation, implied warranty, condition or other term, or any duty at common law or under express terms of this contract, be liable for any loss of profit or any indirect, special or consequential loss, damage, costs, expenses or other claims (whether caused by the Supplier’s servants or agents or otherwise) in connection with the performance of this contract or with the use by the Client of the Services supplied.</p>
<p class="p2"><span class="s1">9.2 </span>The Client shall indemnify the Supplier against all damages, costs, claims and expenses suffered by the Supplier arising from loss or damage to any equipment (including that of third parties) caused by the Client, or its agent or employees.</p>
<p class="p2"><span class="s1">9.3 </span>The Supplier shall not be liable to the Client or be deemed to be in breach of these terms and conditions by reason of any delay in performing, or any failure to perform, any of the Supplier’s obligations if the delay or failure was due to any cause beyond the Supplier’s reasonable control.</p>
<p class="p3"><span class="s1">9.4 </span>[Where the Client consists of two or more persons such expression throughout shall mean and include such two or more persons and each or any of them. All obligations on the part of such a Client shall be joint and several obligations of such persons.]</p>
<p class="p1"><strong>10. <strong>Force Majeure</strong></strong></p>
<p class="p2"><span class="s1">10.1 </span>Neither the Supplier nor the Client shall be liable to the other or be deemed to be in breach of the Contract by reason of any delay in performing, or any failure to perform, any of its obligations in relation to the Services, if the delay or failure was due to any cause beyond that party’s reasonable control. Without prejudice to the generality of the foregoing, the following shall be regarded as causes beyond either party’s reasonable control: –</p>
<p class="p2"><span class="s1">10.2 </span>act of God, explosion, flood, tempest, fire or accident;</p>
<p class="p2"><span class="s1">10.3 </span>war or threat of war, sabotage, insurrection, civil disturbance or requisition;</p>
<p class="p2"><span class="s1">10.4 </span>acts, restrictions, regulations, bye-laws, prohibitions or measures of any kind on the part of any governmental, parliamentary or local authority; 10.5 import or export regulations or embargoes;</p>
<p class="p2"><span class="s1">10.6 </span>strikes, lock-outs, or other industrial actions or trade disputes (whether involving employees of either the Supplier or the Client or of a third party);</p>
<p class="p3"><span class="s1">10.7 </span>difficulties in obtaining raw materials, labour, fuel, part or machinery; 10.8 power failure or breakdown in machinery.</p>
<p class="p1"><strong>11. <strong>Waiver</strong></strong></p>
<p class="p2"><span class="s1">11.1 </span>No waiver by the Client of any breach of these terms and conditions by the Supplier shall be considered as a waiver of any subsequent breach of the same or any other provision. A waiver of any term, provision or condition of this agreement shall be effective only if given in writing and signed by the waiving party and then only in the instance and for the purpose for which the waiver is given.</p>
<p class="p3"><span class="s1">11.2 </span>No failure or delay on the part of any party in exercising any right, power or privilege under this agreement shall operate as a waiver of, nor shall any single or partial exercise of any such right, power or privilege preclude any other or further exercise of or the exercise of any other right, power or privilege.</p>
<p class="p1"><strong>12. <strong>Severance</strong></strong></p>
<p class="p1">If any provision of these terms and conditions is held by any competent authority to be invalid or unenforceable in whole or in part the validity of the other provisions of these terms and conditions and the remainder of the provision in question shall not be affected thereby.</p>
<p class="p1"><strong>13. <strong>Copyright</strong></strong></p>
<p class="p1">The Client reserves all copyright and any other rights (if any) which may subsist in the products of, or in connection with, the provision of the Supplier’s services or facilities. The Client reserves the right to take such actions as may be appropriate to restrain or prevent infringement of such copyright.</p>
<p class="p1"><strong>14. <strong>Notices and Service</strong></strong></p>
<p class="p2"><span class="s1">14.1 </span>Any notice or other information required or authorised by this Agreement to be given by either party to the other shall be given by sending via pre-paid registered post, email, facsimile transmission or other comparable means of communication.</p>
<p class="p2"><span class="s1">14.2 </span>Any notice or information given by post in the manner provided by Clause 14.1 which is not returned to the sender as undelivered shall be deemed to have been given on the SEVEN working days after the envelope containing it was so posted; and proof that the envelope containing any such notice or information was properly addressed, pre-paid, registered and posted, and that it has not been so returned to the sender, shall be sufficient evidence that the notice or information has been duly given.</p>
<p class="p2"><span class="s1">14.3 </span>Any notice or information sent by e-mail, telex, cable, facsimile transmission or comparable means of communication shall be deemed to have been duly given on the date of transmission, provided that a confirming copy of it is sent to the other party 24 hours after transmission.</p>
<p class="p3"><span class="s1">14.4 </span>Service of any document for the purposes of any legal proceedings concerning or arising out of this Agreement shall be effected by either party by causing such document to be delivered to the other party at its registered or principal office, or to such other address as may be notified to one party by the other party in writing from time to time</p>
<p class="p1"><strong>15. <strong>Applicable Law and Jurisdiction</strong></strong></p>
<p class="p1">These terms and conditions shall be governed and construed in accordance with English and Welsh law and the parties shall submit to the non-exclusive jurisdiction of the English and Welsh courts.</p>
<p class="p1"><b>All other works and services, whether express or implied, are hereby excluded. </b></p>
	</div>
</div>