<?php

/** @var \SuttonBaker\Impresario\Block\Cost\PrintPO $block **/
?>

<div class="container bg-white p-4">
    <div class="row pb-4">
        <!-- Left column start -->
        <div class="col-md">
            <!-- Logo and address -->
            <div class="pb-2">
                <div class="w-50">
                    <img src="<?php echo $block->getLogo(); ?>" class="img-fluid" />
                </div>

                Camp Farm Barn,<br />
                Knowle Hill,<br />
                Hurley,<br />
                CV9 2JF
            </div>

        </div>
        <!-- Left column end -->

        <!-- Right column start - bootstrap resets print table backgrounds, hence they're inlined here -->
        <div class="col-md">
            <table class="table table-sm table-bordered border-dark">
                <tr>
                    <th class="bg-secondary text-white" style="background: #6c757d !important;">Date:</th>
                    <td><?= $block->escapeHtml($block->getCostDate()); ?></td>
                </tr>

                <tr>
                    <th class="bg-secondary text-white" style="background: #6c757d !important;">Project No:</th>
                    <td><?= $block->escapeHtml($block->getCost()->getParentId()); ?></td>
                </tr>

                <tr>
                    <th class="bg-secondary text-white" style="background: #6c757d !important;">Client:</th>
                    <td><?= $block->escapeHtml($block->getClientName()); ?></td>
                </tr>

                <tr>
                    <th class="bg-secondary text-white" style="background: #6c757d !important;">Supplier Order Number:</th>
                    <td><?= $block->escapeHtml($block->getCost()->getCostNumber()); ?></td>
                </tr>

                <tr>
                    <th class="bg-secondary text-white" style="background: #6c757d !important;">PO Number:</th>
                    <td><?= $block->escapeHtml($block->getCost()->getId()) ?></td>
                </tr>
            </table>
        </div>
    </div>

    <div class="row flex d-flex h-100 pb-4">
        <div class="col-md">
            <div class="border border-dark d-flex flex-column h-100">
                <div class="bg-secondary text-white p-1">Supplier</div>
                <!--This is already escaped by the block -->
                <div class="p-1"><?= $block->getSupplierAddress(); ?></div>
            </div>
        </div>

        <div class="col-md">
            <div class="border border-dark d-flex flex-column h-100">
                <div class="bg-secondary text-white p-1">Site</div>
                <div class="p-1"><?= $block->escapeHtml($block->getSiteName()); ?></div>
            </div>
        </div>
    </div>

    <div class="row pb-4">
        <div class="col">
            <table class="table table-sm table-bordered border-dark">
                <tr>
                    <th class="bg-secondary text-white" style="background: #6c757d !important;">Requested By (PM):</th>
                    <td class="w-50"><?= $block->escapeHtml($block->getProjectManagerName()); ?></td>
                </tr>
            </table>
        </div>
    </div>
</div>