<?php /** @var \DaveBaker\Core\Block\Html\Heading $block */ ?>
<div class="pageheader">


    <h2><i class="fa fa-file-o" style="line-height: 48px;padding-left: 2px;"></i> <?php echo $block->getHeading();?></h2>


    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>You are here</li>
            <li><a href="index.html">Minimal</a></li>
            <li><a href="#">Example Pages</a></li>
            <li class="active">Blank Page</li>
        </ol>
    </div>


</div>