<?php
/** @var \DaveBaker\Form\Block\Form $block */
?>

<section class="tile color transparent-black">
    <div class="tile-widget nopadding color transparent-black rounded-top-corners">
        <ul class="nav nav-tabs tabdrop"><li class="dropdown pull-right tabdrop hide"><a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-th-list"></i> <span class="badge"></span></a><ul class="dropdown-menu"></ul></li>
            <li class="active"><a href="#tab1" data-toggle="tab"><?php echo $block->getTitle();?></a></li>

        </ul>
    </div>
    <div class="tile-body">
        <div class="tab-content">
            <div class="tab-pane-active">
                <form
                    name="<?php echo $block->escAttr($block->getElementName());?>"
                    method="<?php echo $block->escAttr($block->getFormMethod());?>"
                    action="<?php echo $block->escAttr($block->getFormAction());?>"
                    <?php echo $block->getAttrs();?> class="form-horizontal form1" >

                    <?php foreach($block->getChildBlocks() as $childBlock):?>
                        <div class="form-group">
                            <?php echo $childBlock->render();?>
                        </div>
                    <?php endforeach;?>
                </form>
            </div>
        </div>
    </div>
</section>