<?php
/** @var \DaveBaker\Core\Block\Html\Table $block */
?>
<?php if($this->getRecords()): ?>
    <table <?php echo $block->getAttrs(); ?>>

        <?php if($this->getHeaders()): ?>
            <thead>
            <tr>
                <?php foreach($block->getHeaders() as $header): ?>
                    <th><?php echo $block->escapeHtml($header); ?></th>
                <?php endforeach;?>
            </tr>
            </thead>


            <tbody>
            <?php foreach($block->getRecords() as $record): ?>
                <tr class="<?php echo $block->getRowClass($record);?>">
                    <?php foreach($block->getHeaderKeys() as $k => $header): ?>
                        <td>
                            <?php if($link = $block->getlink($record)):?>
                                <a href="<?php echo $link;?>">
                            <?php endif;?>

                            <?php echo $this->escapeHtml($record->getOutputData($header), $header); ?>

                            <?php if($link):?>
                                </a>
                            <?php endif;?>
                        </td>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
            </tbody>
        <?php endif; ?>
    </table>
<?php endif; ?>