<?php
/** @var SuttonBaker\Impresario\Block\Table\StatusLink $block */
?>
<?php if($this->getRecords()): ?>
    <table <?php echo $block->getAttrs(); ?>>

        <?php if($this->getHeaders()): ?>
            <thead>
            <tr>
                <?php foreach($block->getHeaders() as $k => $header): ?>
                    <th <?php echo $block->getThAttrs($k);?>><?php echo $block->escapeHtml($header); ?></th>
                <?php endforeach;?>
            </tr>
            </thead>

            <tbody>
            <?php foreach($block->getRecords() as $record): ?>
                <tr class="<?php echo $block->getRowClass($record);?>">
                    <?php foreach($block->getHeaderKeys() as $k => $header): ?>
                        <td <?php echo $block->getTdAttrs($k);?>>
                            <?php if($link = $block->getLink($k, $record)):?>
                                <a href="<?php echo $link;?>" <?php echo $block->getAnchorAttrs($k);?>>
                            <?php endif;?>

                            <?php echo $this->escapeHtml($record->getOutputData($header), $header); ?>

                            <?php if($link):?>
                                </a>
                            <?php endif;?>
                        </td>
                    <?php endforeach; ?>
                </tr>
                <tr class="<?php echo $block->getRowClass($record);?> borderless">
                    <td colspan="<?php echo count($this->getHeaders());?>" class="pt-0">
                        <?php if($link = $block->getLink($k, $record)):?>
                            <a href="<?php echo $link;?>" <?php echo $block->getAnchorAttrs($k);?>>
                        <?php endif;?>

                        <?php echo $block->escapeHtml($record->getDescription()); ?>

                        <?php if($link):?>
                            </a>
                        <?php endif;?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        <?php endif; ?>
    </table>
<?php endif; ?>