<?php
/** @var $block \DaveBaker\Core\Block\Html\Table */
$block->addClass('table table-datatable table-custom dataTable');
?>
<section class="tile transparent">
<div class="tile-body color transparent-black rounded-corners">
<div class="table-responsive-does-not-work">
<div class="dataTables_wrapper form-inline">
<table <?php echo $block->getAttrs();?>>

    <?php if($this->getHeaders()):?>
        <thead>
            <tr>
                <?php foreach($block->getHeaders() as $header):?>
                    <th><?php echo $block->escapeHtml($header);?></th>
                <?php endforeach;?>
            </tr>
        </thead>


        <tbody>
            <?php foreach($block->getRecords() as $record):?>
            <tr>
                <?php foreach($block->getHeaderKeys() as $k => $header):?>
                    <td><?php echo $this->escapeHtml($record->getData($header), $header); ?></td>
                <?php endforeach; ?>
            </tr>
            <?php endforeach; ?>
        </tbody>
    <?php endif; ?>

</table>
</div>
</div>
</div>
</section>