<?php
/** @var $block \DaveBaker\Core\Block\Html\Messages */
?>
<?php if($messagesTypes = $block->getMessages()):?>
    <div <?php echo $block->getAttrs();?>>
        <?php foreach($messagesTypes as $type => $messages):?>
            <?php if(count($messages)):?>
                <div class="notification notification-<?php echo $type;?> ">
                    <ul class="notification-list">
                        <?php foreach($messages as $message):?>
                            <li>
                                <?php echo $block->escapeHtml($block->_($message));?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif;?>
        <?php endforeach; ?>
    </div>
<?php endif; ?>